### ISSUE TITLE
Syntax highlighting glitch with equal sign

### ISSUE THREAD

**Issue by SystemDisc** [princemaple/ngx-html-syntax#18]
<a href="https://imgur.com/a/lg0Rr" target="_blank"><img src="https://i.imgur.com/uJ85Kto.png"></a>
<a href="https://imgur.com/a/lg0Rr" target="_blank"><img src="https://i.imgur.com/GFxd8LA.png"></a>
<a href="https://imgur.com/a/lg0Rr" target="_blank"><img src="https://i.imgur.com/Wbc5Ugl.png"></a>

**Comment by princemaple** [comment]
Could you report your ST version? If you aren't on dev build (3156) this is expected to break. You might want to clone an older version for now.

**Comment by SystemDisc** [comment]
Oh, I'm on 3143  
Thanks for the info!

**Comment by princemaple** [comment]
https://github.com/princemaple/ngx-html-syntax/commit/7974b5dd2e36cedefe849c014817963f86b49d8f this commit should be good.

**Comment by SystemDisc** [comment]
Thanks!

I have noticed some syntax highlighting errors when switching to ST 3 - 3156, however.

Here are examples:
<a href="https://imgur.com/a/lg0Rr"><img src="https://i.imgur.com/jk96JkV.png">  
<img src="https://i.imgur.com/3frGKE1.png"></a>

There were others I ran into yesterday, but I can't remember the context

**Comment by SystemDisc** [comment]
Thanks for the awesome work!

**Comment by princemaple** [comment]
@SystemDisc some of the incorrect highlightings are not fixable, since I'm simply delegating to js syntax whenever appropriate (i.e. when in Angular expression context, like interpolation, bindings, etc)
My experience is that the rare slightly wrong highlightings are not crucial, I've been simply ignoring some of them. I had tried to locate the errors. I inspected every scope that was not 100% correct and could not find out why. This could be some lower level glitches in Sublime that need to / might be polished away in the future. :|

**Comment by SystemDisc** [comment]
Thanks for the helpful information! You may close this issue as wontfix if you want :)

**Comment by princemaple** [comment]
:) I'll leave this open until next ST stable/beta is released, by then everyone will have access to the new syntax features, and the wrong highlights are up to ST to fix after that.

**Comment by princemaple** [comment]
![image](https://user-images.githubusercontent.com/1329716/36053938-f04ec8c2-0e47-11e8-94a7-6e1ed2762f09.png)
This might be the fix for it! I did a quick test, seems to be good. I'm not certain if it covers all the cases without going through more files, but it surely sounds promising.
