### ISSUE TITLE
Control block improvements

### ISSUE THREAD

**Issue by princemaple** [princemaple/ngx-html-syntax#30]
Currently this package highlights simple code like below correctly

```
@if (a) {
  some text
} @else {
  some other text
}
```

However, with signal API being stabilized, there will be more code like

```
@if (a()) {
  some text
} @else {
  some other text
}
```

The signal syntax breaks the syntax highlighting at the moment. Same goes for `@switch`, `@for`, etc.

The syntax needs to be improved to accept more general JS(TS) code in the brackets.

Can we get some help from you @deathaxe ?

**Comment by deathaxe** [comment]
A fix requires proper implementation of [Angular Expression Syntax](https://angular.dev/guide/templates/expression-syntax), which is a subset of JavaScript, but with some specials like pipes `| filter` etc.

May take a bit to get something crafted.

**Comment by princemaple** [comment]
Thanks for the reply! I thought there was some simpler hack that can utilize the existing ts syntax, I guess not then. That does sound like some major work. No worries at all.

**Comment by deathaxe** [comment]
We could include js expressions into groups, to get most things working, but it might still break on those special keywords like `async` etc.

As only basic javascript seems to be supported it might be more safe to just implement that subset drectly, instead of relying on whole JavaScript. Jinja and Twig use that way to have full control.

Using JS expressions, unsupported stuff like arrow functions and class definitions are highlighted as false positives, currently.

I guess it shouldn't be too complicated though.

**Comment by princemaple** [comment]
Yeah the only thing is we'd have to keep up with angular updates. I guess it's bearable, it's infrequent that new allowed syntax is added. This control block thing is the only major addition in maybe 4 or 5 years.
